"""
Deploy Endpoint — Handles deployment of generated applications.

Supports:
- File download (ZIP archive)
- Vercel deployment (via API)
- Render deployment (via API)
"""

import io
import json
import zipfile
import logging

from fastapi import APIRouter, HTTPException
from fastapi.responses import StreamingResponse
from pydantic import BaseModel

logger = logging.getLogger(__name__)
router = APIRouter()


class DeployRequest(BaseModel):
    code_blocks: dict[str, str]
    app_name: str = "generated-app"
    target: str = "download"  # "download" | "vercel" | "render"


class DeployResponse(BaseModel):
    status: str
    message: str
    url: str | None = None


@router.post("/deploy", response_model=DeployResponse)
async def deploy_application(request: DeployRequest):
    """Deploy generated code to the specified target."""

    if request.target == "download":
        return DeployResponse(
            status="ready",
            message="Use GET /deploy/download to download the ZIP archive.",
            url=None,
        )

    elif request.target == "vercel":
        # TODO: Implement Vercel API deployment
        raise HTTPException(
            status_code=501,
            detail="Vercel deployment not yet implemented. Use 'download' target.",
        )

    elif request.target == "render":
        # TODO: Implement Render API deployment
        raise HTTPException(
            status_code=501,
            detail="Render deployment not yet implemented. Use 'download' target.",
        )

    raise HTTPException(
        status_code=400,
        detail=f"Unknown deploy target: {request.target}",
    )


@router.post("/deploy/download")
async def download_generated_code(request: DeployRequest):
    """Package generated code as a downloadable ZIP archive."""

    if not request.code_blocks:
        raise HTTPException(status_code=400, detail="No code blocks provided")

    # Create ZIP in memory
    zip_buffer = io.BytesIO()
    with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zf:
        for filename, content in request.code_blocks.items():
            zf.writestr(filename, content)

        # Add a README
        readme = _generate_readme(request.app_name, request.code_blocks)
        zf.writestr("README.md", readme)

    zip_buffer.seek(0)

    return StreamingResponse(
        zip_buffer,
        media_type="application/zip",
        headers={
            "Content-Disposition": f"attachment; filename={request.app_name}.zip"
        },
    )


def _generate_readme(app_name: str, code_blocks: dict[str, str]) -> str:
    """Generate a basic README for the downloaded project."""
    file_list = "\n".join([f"- `{f}`" for f in sorted(code_blocks.keys())])

    return f"""# {app_name}

Generated by **AMD AgentForge** — Autonomous AI Application Builder.

## Files

{file_list}

## Quick Start

### Python Backend
```bash
cd backend
pip install -r requirements.txt
python main.py
```

### Node.js Frontend
```bash
cd frontend
npm install
npm run dev
```

## Powered By
- AMD ROCm GPU Acceleration
- LangGraph Multi-Agent Orchestration
- vLLM Inference Engine

---
*Generated automatically. Review all code before deploying to production.*
"""
